# -*- coding: utf-8 -*-
"""NetflixMovie&TVshowReccomendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yI9SxrhVubtL12bbUjG4cfOySugICeLl

#Import Libraries
"""

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import difflib
import requests

"""# Reading Files"""

df = pd.read_csv('https://raw.githubusercontent.com/talia-gordy/downloaded-datasets/refs/heads/main/titles.csv')

"""#Getting Features"""

df_features = df[['title','type','description','release_year','age_certification','genres','seasons','imdb_score']].fillna("")

df_features = df_features.rename(columns={'release_year': 'release_date', 'age_certification': 'rating'})

x = df_features['title'].astype(str) + ' ' + df_features['type'].astype(str) + ' ' + df_features['release_date'].astype(str) + ' ' + df_features['rating'].astype(str) + ' ' + df_features['genres'].astype(str) + ' ' + df_features['seasons'].astype(str) + ' ' + df_features['imdb_score'].astype(str)

"""# Conversion to Tokens"""

tfidf = TfidfVectorizer()

x = tfidf.fit_transform(x)

"""# Get Similarity Score"""

Similarity_Score = cosine_similarity(x)

def get_poster(title):
    # OMDB API - get your free API key from http://www.omdbapi.com/
    api_key = 'your_omdb_api_key_here'  # Replace with your API key
    url = f"http://www.omdbapi.com/?t={title}&apikey={api_key}"
    try:
        response = requests.get(url)
        data = response.json()
        if data.get('Poster') and data['Poster'] != 'N/A':
            return data['Poster']
    except:
        pass
    return None  # Placeholder if no poster

def recommend(user_input):
    All_Movies_TVshow_List = df['title'].fillna('').astype(str).tolist()
    
    exact_match_found = False
    if user_input in All_Movies_TVshow_List:
        Close_Match = user_input
        exact_match_found = True
    else:
        Find_Close_Match = difflib.get_close_matches(user_input, All_Movies_TVshow_List)
        if Find_Close_Match:
            Close_Match = Find_Close_Match[0]
        else:
            return [{"error": f"Sorry, '{user_input}' and similar titles were not found in the database. Please try another name."}]
    
    Index_of_Movie_TVshow = df[df.title == Close_Match].index[0]
    Recommendation_Score = list(enumerate(Similarity_Score[Index_of_Movie_TVshow]))
    sorted_similar_movies_tvshows = sorted(Recommendation_Score, key=lambda x: x[1], reverse=True)
    
    recommendations = []
    i = 1
    for movie_TVshows in sorted_similar_movies_tvshows:
        index = movie_TVshows[0]
        if df.index[index] != Index_of_Movie_TVshow:
            row = df.loc[index]
            title = row['title']
            poster = get_poster(title)
            rec = {
                'title': title,
                'poster': poster,
                'description': row['description'],
                'release_year': row['release_year'],
                'rating': row['age_certification'],
                'genres': row['genres'],
                'seasons': row['seasons'],
                'imdb_score': row['imdb_score']
            }
            if i <= 10:
                recommendations.append(rec)
                i += 1
            else:
                break
    return recommendations